---
- hosts: database # Hosts que o ansible vai utilizar
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: "Instala todas as dependencias"
      apt:
        name: "{{ item }}"
        state: latest # estado desejado da execução da task. Toda task é checado um estado. nesse caso ele vai instalar o php5 mais novo
        update_cache: yes # atualizar o cache do apt (apt update)
      become: yes # fazer como usuario root
      with_items:
        - mysql-server-5.7
        # - python-mysqldb
        - python3-mysqldb
        - python3-pip

    # Instalar o python-mysql; requerido pelo ansible para conectar com o mysql
    - name: "Instala o modulo pymysql"
      pip:
        name:
          - pymysql
        state: latest
      become: yes

    - name: "Cria o banco no MySQL"
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ wp_db_name }}" # nome do banco
        login_user: root # usuario do banco
        # login_password: senha_do_banco
        state: present # criar o banco. present, absent, dump, import
      become: yes

    - name: "Cria o usuario do MySQL"
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ wp_db_user }}"
        login_user: root
        password: "{{ wp_db_pass }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: "{{ item }}"
      become: yes
      with_items:
        - "localhost"
        - "127.0.0.1"
        - "{{ wp_host_ip }}" # ip do servidor que possui o wordpress

    # Aceitar conexoes remotas
    - name: "Copia o arquivo mysqld.cnf"
      copy:
        src: "files/mysqld.cnf"
        dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
      become: yes
      notify:
        - restart mysql

- hosts: wordpress

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks: # Lista de comandos
    # Escreve hello world em um txt
    # - name: 'Escreva hello world'
    #   shell: 'echo helo world >> $HOME/arquivo.txt'

    - name: "Instala todas as dependencias"
      apt:
        name: "{{ item }}"
        state: latest # estado desejado da execução da task. Toda task é checado um estado. nesse caso ele vai instalar o php5 mais novo
        update_cache: yes # atualizar o cache do apt (apt update)
      become: yes # fazer como usuario root
      with_items:
        - php7.2
        - apache2
        - libapache2-mod-php7.2 # Modulo de integracao entre o php e o apache
        - php7.2-gd
        # - libssh2-php
        # - php5-mcrypt
        - mcrypt
        - php7.2-mysql

    # Configurar o wordpress
    - name: "Baixa o arquivo de instalacao do Wordpress"
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: "Descompacta o arquivo de instalacao do Wordpress"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes # arquivo sera baixado do servidor remoto (yes), ou sera baixado do local (no)
        # creates: /var/www/html/wordpress/wp-settings.php
      become: yes

    - name: "copia wp-config"
      copy:
        src: "{{ wp_install_dir }}/wp-config-sample.php"
        dest: "{{ wp_install_dir }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: "Configura variaveis do wp-config"
      replace:
        path: "{{ wp_install_dir }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: "database_name_here", value: "{{ wp_db_name }}" }
        - { regex: "username_here", value: "{{ wp_db_user }}" }
        - { regex: "password_here", value: "{{ wp_db_pass }}" }
        - { regex: "localhost", value: "{{ wp_db_ip }}" } # ip privado da instancia que possui o banco
      become: yes

    - name: "Copia o arquivo de configuracao do apache"
      template:
        src: "templates/000-default.conf.j2"
        dest: "/etc/apache2/sites-available/000-default.conf"
        # remote_src: no
      become: yes
      notify:
        - restart apache
