---
# Configurar o wordpress
- name: "Baixa o arquivo de instalacao do Wordpress"
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: "Descompacta o arquivo de instalacao do Wordpress"
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes # arquivo sera baixado do servidor remoto (yes), ou sera baixado do local (no)
    # creates: /var/www/html/wordpress/wp-settings.php
  become: yes

- name: "copia wp-config"
  copy:
    src: "{{ wp_install_dir }}/wp-config-sample.php"
    dest: "{{ wp_install_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "Configura variaveis do wp-config"
  replace:
    path: "{{ wp_install_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
    backup: yes
  with_items:
    - { regex: "database_name_here", value: "{{ wp_db_name }}" }
    - { regex: "username_here", value: "{{ wp_db_user }}" }
    - { regex: "password_here", value: "{{ wp_db_pass }}" }
    - { regex: "localhost", value: "{{ wp_db_ip }}" } # ip privado da instancia que possui o banco
  become: yes

- name: "Copia o arquivo de configuracao do apache"
  template:
    src: "templates/000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
    # remote_src: no
  become: yes
  notify:
    - restart apache
